# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'neighbor' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for neighbor
  platform :ios, ‘9.0’
  pod 'Firebase'
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'
  pod 'GoogleSignIn'
  pod 'Firebase/Storage'
  pod 'Firebase/Messaging'
  pod 'Firebase/Firestore'
  target 'neighbor-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'neighborTests' do
    inherit! :search_paths
    # Pods for testing
  end

end